### ISSUE TITLE
Error on Invoke-MDMReenrollment

### ISSUE THREAD

**Issue by samverstraete** [ztrhgf/useful_powershell_functions#3]
Hi 
Thanks for these great scripts! 

I'm getting this error when running Invoke-MDMReenrollment or Reset-IntuneEnrollment:

> Error message: Unable to obtain enrollment GUID value from task scheduler. Aborting

![Schermafbeelding 2023-01-27 155942](https://user-images.githubusercontent.com/8677006/215483954-3a4c8a1e-4d64-4ebb-be2d-b16293c3c2c9.png)

Any idea what I'm doing wrong or what the problem could be? These are Hybrid Joined devices...

**Comment by ztrhgf** [comment]
Hard to say, sorry.
