### ISSUE TITLE
Error on Get-IntuneReport.ps1

### ISSUE THREAD

**Issue by weberchr** [ztrhgf/useful_powershell_functions#7]
Error since abt. a month:

WARNING: Requesting the report Devices
Invoke-RestMethod: C:\actions-runner\_work\...\....\Intune\Get-IntuneReport.ps1:166
Line |
 166 |  …   $result = Invoke-RestMethod -Headers $header -Uri "https://graph.mi …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":{"code":"UnsupportedMediaType","message":"An error has
     | occurred.","details":[],"innerError":{"date":"2024-[12](https://github.gsissc.myatos.net/..../actions/runs/371953/job/742481#step:4:13)-02T07:53:34","request-id":"c5ece965-26d1-4dcd-b957-6965e24e09cc","client-request-id":"c5ece965-26d1-4dcd-b957-6965e24e09cc"}}}
Error: Process completed with exit code 1.

Running on local git runner WinX64.

**Comment by ztrhgf** [comment]
Thanks for reporting. 

This should be fixed in the new module version https://www.powershellgallery.com/packages/IntuneStuff/1.6.1

**Comment by weberchr** [comment]
Hi,

thanks for reply. It works again now.

BR
Christian

Von: Ondrej Sebela ***@***.***>
Gesendet: Montag, 2. Dezember 2024 13:51
An: ztrhgf/useful_powershell_functions ***@***.***>
Cc: Christian Weber ***@***.***>; Author ***@***.***>
Betreff: Re: [ztrhgf/useful_powershell_functions] Error on Get-IntuneReport.ps1 (Issue #7)

Caution: External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.


Thanks for reporting.

This should be fixed in the new module version https://www.powershellgallery.com/packages/IntuneStuff/1.6.1
